package io.github.caiohbs.gbemu.cartridge.mappers;

import java.util.Map;


public final class OldLicenseeCodes {

    public static final Map<Integer, String> TYPES = Map.<Integer, String>ofEntries(
            Map.entry(0x00, "None"),
            Map.entry(0x01, "Nintendo"),
            Map.entry(0x08, "Capcom"),
            Map.entry(0x09, "HOT-B"),
            Map.entry(0x0A, "Jaleco"),
            Map.entry(0x0B, "Coconuts Japan"),
            Map.entry(0x0C, "Elite Systems"),
            Map.entry(0x13, "EA (Electronic Arts)"),
            Map.entry(0x18, "Hudson Soft"),
            Map.entry(0x19, "ITC Entertainment"),
            Map.entry(0x1A, "Yanoman"),
            Map.entry(0x1D, "Japan Clary"),
            Map.entry(0x1F, "Virgin Games Ltd.3"),
            Map.entry(0x24, "PCM Complete"),
            Map.entry(0x25, "San-X"),
            Map.entry(0x28, "Kemco"),
            Map.entry(0x29, "SETA Corporation"),
            Map.entry(0x30, "Infogrames5"),
            Map.entry(0x31, "Nintendo"),
            Map.entry(0x32, "Bandai"),
            Map.entry(0x33, "Indicates that the New licensee code should be used instead."),
            Map.entry(0x34, "Konami"),
            Map.entry(0x35, "HectorSoft"),
            Map.entry(0x38, "Capcom"),
            Map.entry(0x39, "Banpresto"),
            Map.entry(0x3C, "Entertainment Interactive (stub)"),
            Map.entry(0x3E, "Gremlin"),
            Map.entry(0x41, "Ubi Soft1"),
            Map.entry(0x42, "Atlus"),
            Map.entry(0x44, "Malibu Interactive"),
            Map.entry(0x46, "Angel"),
            Map.entry(0x47, "Spectrum HoloByte"),
            Map.entry(0x49, "Irem"),
            Map.entry(0x4A, "Virgin Games Ltd.3"),
            Map.entry(0x4D, "Malibu Interactive"),
            Map.entry(0x4F, "U.S. Gold"),
            Map.entry(0x50, "Absolute"),
            Map.entry(0x51, "Acclaim Entertainment"),
            Map.entry(0x52, "Activision"),
            Map.entry(0x53, "Sammy USA Corporation"),
            Map.entry(0x54, "GameTek"),
            Map.entry(0x55, "Park Place15"),
            Map.entry(0x56, "LJN"),
            Map.entry(0x57, "Matchbox"),
            Map.entry(0x59, "Milton Bradley Company"),
            Map.entry(0x5A, "Mindscape"),
            Map.entry(0x5B, "Romstar"),
            Map.entry(0x5C, "Naxat Soft16"),
            Map.entry(0x5D, "Tradewest"),
            Map.entry(0x60, "Titus Interactive"),
            Map.entry(0x61, "Virgin Games Ltd.3"),
            Map.entry(0x67, "Ocean Software"),
            Map.entry(0x69, "EA (Electronic Arts)"),
            Map.entry(0x6E, "Elite Systems"),
            Map.entry(0x6F, "Electro Brain"),
            Map.entry(0x70, "Infogrames5"),
            Map.entry(0x71, "Interplay Entertainment"),
            Map.entry(0x72, "Broderbund"),
            Map.entry(0x73, "Sculptured Software6"),
            Map.entry(0x75, "The Sales Curve Limited7"),
            Map.entry(0x78, "THQ"),
            Map.entry(0x79, "Accolade8"),
            Map.entry(0x7A, "Triffix Entertainment"),
            Map.entry(0x7C, "MicroProse"),
            Map.entry(0x7F, "Kemco"),
            Map.entry(0x80, "Misawa Entertainment"),
            Map.entry(0x83, "LOZC G."),
            Map.entry(0x86, "Tokuma Shoten"),
            Map.entry(0x8B, "Bullet-Proof Software2"),
            Map.entry(0x8C, "Vic Tokai Corp.17"),
            Map.entry(0x8E, "Ape Inc.18"),
            Map.entry(0x8F, "I’Max19"),
            Map.entry(0x91, "Chunsoft Co.9"),
            Map.entry(0x92, "Video System"),
            Map.entry(0x93, "Tsubaraya Productions"),
            Map.entry(0x95, "Varie"),
            Map.entry(0x96, "Yonezawa10/S’Pal"),
            Map.entry(0x97, "Kemco"),
            Map.entry(0x99, "Arc"),
            Map.entry(0x9A, "Nihon Bussan"),
            Map.entry(0x9B, "Tecmo"),
            Map.entry(0x9C, "Imagineer"),
            Map.entry(0x9D, "Banpresto"),
            Map.entry(0x9F, "Nova"),
            Map.entry(0xA1, "Hori Electric"),
            Map.entry(0xA2, "Bandai"),
            Map.entry(0xA4, "Konami"),
            Map.entry(0xA6, "Kawada"),
            Map.entry(0xA7, "Takara"),
            Map.entry(0xA9, "Technos Japan"),
            Map.entry(0xAA, "Broderbund"),
            Map.entry(0xAC, "Toei Animation"),
            Map.entry(0xAD, "Toho"),
            Map.entry(0xAF, "Namco"),
            Map.entry(0xB0, "Acclaim Entertainment"),
            Map.entry(0xB1, "ASCII Corporation or Nexsoft"),
            Map.entry(0xB2, "Bandai"),
            Map.entry(0xB4, "Square Enix"),
            Map.entry(0xB6, "HAL Laboratory"),
            Map.entry(0xB7, "SNK"),
            Map.entry(0xB9, "Pony Canyon"),
            Map.entry(0xBA, "Culture Brain"),
            Map.entry(0xBB, "Sunsoft"),
            Map.entry(0xBD, "Sony Imagesoft"),
            Map.entry(0xBF, "Sammy Corporation"),
            Map.entry(0xC0, "Taito"),
            Map.entry(0xC2, "Kemco"),
            Map.entry(0xC3, "Square"),
            Map.entry(0xC4, "Tokuma Shoten"),
            Map.entry(0xC5, "Data East"),
            Map.entry(0xC6, "Tonkin House"),
            Map.entry(0xC8, "Koei"),
            Map.entry(0xC9, "UFL"),
            Map.entry(0xCA, "Ultra Games"),
            Map.entry(0xCB, "VAP, Inc."),
            Map.entry(0xCC, "Use Corporation"),
            Map.entry(0xCD, "Meldac"),
            Map.entry(0xCE, "Pony Canyon"),
            Map.entry(0xCF, "Angel"),
            Map.entry(0xD0, "Taito"),
            Map.entry(0xD1, "SOFEL (Software Engineering Lab)"),
            Map.entry(0xD2, "Quest"),
            Map.entry(0xD3, "Sigma Enterprises"),
            Map.entry(0xD4, "ASK Kodansha Co."),
            Map.entry(0xD6, "Naxat Soft16"),
            Map.entry(0xD7, "Copya System"),
            Map.entry(0xD9, "Banpresto"),
            Map.entry(0xDA, "Tomy"),
            Map.entry(0xDB, "LJN"),
            Map.entry(0xDD, "Nippon Computer Systems"),
            Map.entry(0xDE, "Human Ent."),
            Map.entry(0xDF, "Altron"),
            Map.entry(0xE0, "Jaleco"),
            Map.entry(0xE1, "Towa Chiki"),
            Map.entry(0xE2, "Yutaka"),
            Map.entry(0xE3, "Varie"),
            Map.entry(0xE5, "Epoch"),
            Map.entry(0xE7, "Athena"),
            Map.entry(0xE8, "Asmik Ace Entertainment"),
            Map.entry(0xE9, "Natsume"),
            Map.entry(0xEA, "King Records"),
            Map.entry(0xEB, "Atlus"),
            Map.entry(0xEC, "Epic/Sony Records"),
            Map.entry(0xEE, "IGS"),
            Map.entry(0xF0, "A Wave"),
            Map.entry(0xF3, "Extreme Entertainment"),
            Map.entry(0xFF, "LJN")
    );

    private OldLicenseeCodes() {
    }

}
